name: sayfuck
version: '${version}'
main: byd.cxkcxkckx.sayfuck.Sayfuck
api-version: '1.20'
description: Chat monitoring plugin using OpenAI API

permissions:
  sayfuck.bypass:
    description: 允许跳过聊天检测
    default: op
